þ	YWXþ	WWþXXWþ	XWþ
XXþ	Xþ

YþYþ		

þþþIþ
•þ
Iøþ
øH–þ–––J–IþõJH–I	þ––I	øþõþ

þ

þ
þ

þøþ
ÿþWWYþUM	XYþY		

þUMLL	XYþMMMMMM
þUMELLH	WYþN<LMMMLM
NþUMELLHLL	WXþ
N9MMMM:9NUMLLLLHJGL	WWþNMMMMMMMNVMLLLLLHLLLLWþMMMMMMNVMLLLLLJHJGLWþ	






WMLLLLLLHLLLWþVMLLLLLLKHKJWþ




WMLLLLLLLHLLWþWMLLLLLLLHKJWþ

WLLLLLLLHLLLWþWLLLLLLLHKGLXþWMLLLLLHLLLLWþ‘WMLLLLHKLLLLXþ‘‘‘OOOOOOWLLLLJJLLLLLXþWLLLJHLLLLLLXþWLLLLHLLCLMLXþWLKKKHLLLLLLXþWGEEFILLILCLXþXWWVWIFDFIILLLXþWUUWWWVWIGDFILLXþ

XUUUUUWWWVWIHFHKXþXUUUUUUUUWWWVVIGHXYþWUUUUUUUUVTWWWVVWXXW	þWUUUUUVSUVTWWWWXXYY	þWUUWSUVSUVTWXYYYYY	õþWWTWSUVSUWYYYY	õþWWTWSUWYYY	õþWWTWYY	õþWY	õþõÿþWWYþUM	XYþY		

þUMLL	XYþMMMMMM
þUMGELL	WYþN<LMMMMM
NþUMGELLLH	WXþ
N:9MMML:NUMLLLLLJHJ	WWþNMMMMMMMNVMLLLLLLHLLLWþMMMMMMNVMLLLLLLKHKJWþ	






WMLLLLLLLHLLWþVMLLLLLLLHKJWþ




WMLLLLLLHLLLWþWMLLLLLLHKGLWþ

WLLLLLLHLLLLWþWLLLLLHKLLLLXþWMLLLJJLLLLLWþ‘WMLLJHLLLLLLXþ‘‘‘OOOOOOWLLLLHLLLLLLXþWLLIKJLLLLJLXþWLLLHLLLIJCJXþWLLLHLLLLLJLXþWIGGHKLLMLILXþXWWVWKHFHKKLLLXþWUUWWWVWKIFHKLLXþ

XUUUUUWWWVWKJHJLXþXUUUUUUUUWWWVVKIJXYþWUUUUUUUUVTWWWVVWXXW	þWUUUUUVSUVTWWWWXXYY	þWUUWSUVSUVTWXYYYYY	õþWWTWSUVSUWYYYY	õþWWTWSUWYYY	õþWWTWYY	õþWY	õþõÿþWWYþUM	XYþY		

þUMLL	XYþML9MMM
þUMJGLL	WYþN<<LMMMM
NþUMJGELLL	WXþ
NL:MMMMMNUMLLELLLLH	WWþNMMMMMMMNVMLLLLLLLHKJWþMMMMMMNVMLLLLLLHLLLWþ	






WMLLLLLLHKGLWþVMLLLLLHLLLLWþ




WMLLLLHKLLLLWþWMLLLJJLLLLLWþ

WLLLJHLLLLLLWþWLLLLHLLLLLLXþWMLIKJLLLLLLWþ‘WMLLHLLLLLLLXþ‘‘‘OOOOOOWLHJHLLLLLLLXþWLLLHLLLLLKLXþWLLHKHLLCKIKXþWLLLLHHLLLKLXþWIGGHKLLMLCLXþXWWVWKHFHKKLLLXþWUUWWWVWKIFHKLLXþ

XUUUUUWWWVWKJHJLXþXUUUUUUUUWWWVVKIJXYþWUUUUUUUUVTWWWVVWXXW	þWUUUUUVSUVTWWWWXXYY	þWUUWSUVSUVTWXYYYYY	õþWWTWSUVSUWYYYY	õþWWTWSUWYYY	õþWWTWYY	õþWY	õþõÿþWWYþUM	XYþY		

þUMLL	XYþMMLMMM
þUMLJLL	WYþN<L<MMMM
NþUMLJGELL	WXþ
NLM:MMMMNUMLLGELLHL	WWþNMM9MMMMNVMLLLLLLHKGLWþMMMMMMNVMLLLLLHLLLLWþ	






WMLLLLHKLLLLWþVMLLLJJLLLLLWþ




WMLLJHLLLLLLWþWMLLLHLLLLLLWþ

WLLIKJLLLLLLWþWLLLHLLLLLLLXþWMHJHLLLLLLLWþ‘WMLLHLLLLLLLXþ‘‘‘OOOOOOWLLHKHLLLLLLXþWLLLLHHLLLLLXþWLLLLHLLILCLXþWLLLLLHLLLLLXþWJHHILLLMLILXþXWWVWLIGILLLLLXþWUUWWWVWLJGILLLXþ

XUUUUUWWWVWLKIKLXþXUUUUUUUUWWWVVLJKXYþWUUUUUUUUVTWWWVVWXXW	þWUUUUUVSUVTWWWWXXYY	þWUUWSUVSUVTWXYYYYY	õþWWTWSUVSUWYYYY	õþWWTWSUWYYY	õþWWTWYY	õþWY	õþõÿþWWYþUM	XYþY		

þUMLL	XYþMMLMMM
þUMLLLL	WYþN<LLMMMM
NþUMLLJGJH	WXþ
NLM<9MMMNUMLLJGEKLL	WWþNMM:LMMMNVMLLLJELLLLLWþMMMMMMNVMLLJHLLLLLLWþ	






WMLLLHLLLLLLWþVMLIKJLLLLLLWþ




WMLLHLLLLLLLWþWMHJHLLLLLLLWþ

WLLLHLLLLLLLWþWLLHKHLLLLLLXþWMLLLHHLLLLLWþ‘WMLLLHLLLLLLXþ‘‘‘OOOOOOWLLLLLHJGLLLXþWLLLLLLLLLLLXþWLLLLLLLMLILXþWLLLLLLLLLLLXþWIGGHKLLCLFLXþXWWVWKHFHKKLLLXþWUUWWWVWKIFHKLLXþ

XUUUUUWWWVWKJHJLXþXUUUUUUUUWWWVVKIJXYþWUUUUUUUUVTWWWVVWXXW	þWUUUUUVSUVTWWWWXXYY	þWUUWSUVSUVTWXYYYYY	õþWWTWSUVSUWYYYY	õþWWTWSUWYYY	õþWWTWYY	õþWY	õþõÿþWWYþUM	XYþY		

þUMLL	XYþMMMMMM
þUMLLLL	WYþN<LMMMMM
NþUMLLLJJL	WXþ
NLMM:9MMNUMLLJHGELL	WWþNMMLMMMMNVMLLLHGELLLLWþMMMMMMNVMLIKJLLLLLLWþ	






WMLLHLLLLLLLWþVMHJHLLLLLLLWþ




WMLLHLLLLLLLWþWMLHKHLLLLLLWþ

WLLLLHHLLLLLWþWLLLLHLLLLLLXþWMLLLLHJGLLLWþ‘WMLLLLLHLLLLXþ‘‘‘OOOOOOWLLLLLLJHJGLXþWLLLLLLLLLLLXþWLLLLLLLCLMLXþWLLLLLLLLLLLXþWHFFGJLLMLJLXþXWWVWJGEGJJLLLXþWUUWWWVWJHEGJLLXþ

XUUUUUWWWVWJIGILXþXUUUUUUUUWWWVVJHIXYþWUUUUUUUUVTWWWVVWXXW	þWUUUUUVSUVTWWWWXXYY	þWUUWSUVSUVTWXYYYYY	õþWWTWSUVSUWYYYY	õþWWTWSUWYYY	õþWWTWYY	õþWY	õþõÿþWWYþUM	XYþY		

þUMLL	XYþMMMMMM
þUMLLLH	WYþN<LMM<9M
NþUMLIKJLL	WXþ
NLMML:<MNUMLLHLLHLL	WWþNMMMMMMMNVMHJHLLHLLLLWþMMMMMMNVMLLHLLLLLLLWþ	






WMLHKHLLLLLLWþVMLLLHHLLLLLWþ




WMLLLHLLLLLLWþWMLLLLHJGLLLWþ

WLLLLLLHLLLLWþWLLLLLLJHJGLXþWMLLLLLLHLLLWþ‘WMLLLLLLKHKJXþ‘‘‘OOOOOOWLLLLLLLLHLLXþWLLLLLLLLLLLXþWLLLLLLLILJLXþWLLLLLLLLLLLXþWGEEFILLLLCLXþXWWVWIFDFIILLLXþWUUWWWVWIGDFILLXþ

XUUUUUWWWVWIHFHKXþXUUUUUUUUWWWVVIGHXYþWUUUUUUUUVTWWWVVWXXW	þWUUUUUVSUVTWWWWXXYY	þWUUWSUVSUVTWXYYYYY	õþWWTWSUVSUWYYYY	õþWWTWSUWYYY	õþWWTWYY	õþWY	õþõÿþWWYþUM	XYþY		

þUMLI	XYþMMMMMM
þUMLLHL	WYþN<LMM<:M
NþUMHJHLLL	WXþ
NLMMMM9MNUMLLHLLLLL	WWþNMMMMMMMNVMLHKHLLLLLLWþMMMMMMNVMLLLHHLLLLLWþ	






WMLLLHLLLLLLWþVMLLLLHJGLLLWþ




WMLLLLLHLLLLWþWMLLLLLJHJGLWþ

WLLLLLLLHLLLWþWLLLLLLLKHKJXþWMLLLLLLLHLLWþ‘WMLLLLLLLHKJXþ‘‘‘OOOOOOWLLLLLLLHLLLXþWLLLLLLJLLLLXþWLLLLLJLMLILXþWKKKLLHLLLLLXþWFDDEHKLCLILXþXWWVWHECEHHLLLXþWUUWWWVWHFCEHKKXþ

XUUUUUWWWVWHGEGJXþXUUUUUUUUWWWVVHFGXYþWUUUUUUUUVTWWWVVWXXW	þWUUUUUVSUVTWWWWXXYY	þWUUWSUVSUVTWXYYYYY	õþWWTWSUVSUWYYYY	õþWWTWSUWYYY	õþWWTWYY	õþWY	õþõÿþ		þõ	þ		þ		
þ	

			þ


					
þõþ	
							þõõõþWVþWUUW			
	HõõõõõþVVXUUUWW		I•HõõõõõþVUWWX			•þþõþ	õþUWþVX•UUY		þõõþ–VUYYXVUWþþõþ•Wþõþþõõþ
þVWþ&þ;õÿþþþþþþ	þ			þ


	

þ
	
	



þñó	
		



óñþ
öóóó

	



óóóñþññóó		



óóóóóñþñöñó
	



óóóóóóóñþñöööñóó
		



óóóóóóññþñöööñóó
	


óóóóñäóñþñöö

öñóó		

óóóóñäóóóñþñóö

öñóó	
óóóóñäóóóóóñþñññóö

öñóóóóóñäóóóóóóññþñóþññóö
öñóääóóóóóóóñóñþñóþññóö
ñóóóóóóóññþóñþñóþññóöñóóóóóññþóñþñóþññóöñóóóññþóñþñóþ	ññóöñóññþóñþñóþóóññþ	óñþóóþóñþ
óñþóñþ
óóþóñþóñþóñþóñþóñþóóÿþòññþòòòññþòòòòññþòòòòññþòòòòññþòòòòññþò	òòòñóþò		
òòóþò		

óþò	

óþò		

óþò			


óþò			


óþò		

óþò

óþòòóþñòòòóþññòòòóþññòòòóþññòòòóþññòòòóþññòòòóþññòóþñÿþóóôþóóôôôþóóôôôôþóóôôôôþóóôôôôþóóôôôôþóôôôôþóôô

ôþó




ôþó
ôþó
ôþó
ôþó
ôþó

ôþó


ôþó



ôôþóôôôóþóôôôóóþóôôôóóþóôôôóóþóôôôóóþóôôôóóþóôóóþóÿþþR

ñþþòR
þþþR

ññ
R

ñþþR

ñòR
R

ñòR
þþR

ñþòR
ñRòR
ñ
R

ñþòR
R
òR

ñ
R

ñòR
þñRR

ñòRR

ñòR
R

ñþQòRòR
R

ñRòR
ñR

ñòR
QQþQRññR
òR
RR
R

ñR
ñR
QþQààòR
ñR
R

ñòR
R
òR
QþRQ°àRñRòR
òR


ñR
R
ðRñXQþQòQQààRñRñR
R
R
RñRQþQ
òòQQààòR
R
RñRáôQþþ
ôòòQQààRñòR
RRRáYôô

QþþòRñôôòòQQààRRñRôôRñ
QþþñRð

ôòòQQáQ
ôô
öR

QþQààRñ
òRñôòò
ôRð
SQþRQ°àà
ñRð

áQô

òRñ
áQRRþQòQQààRñ
òRñRQRñ
öR
RRþQ
òòQàà
ñRð
ñRð
QQáôRþþ
ôòòQàààRñ
òRñQRáYôô

þþòRñôôòòQàà
öRôôRñ
þþñRð

ôòòQàS
ôô
öR

þààRñ
òRñôòò
ôRð
SþRàà
ñRð

áQô

òRñ
áQRþþQàààRñ
òRñRQRñ
öR
Rþþþààà
ñRð
ñRð
QQþþþQàààRñ
òRñQþþþààà
öRþþþ
ààSþ
þþþþþþÿþQþQþñQþ°òñQþ
òðñRQþñþQQ

QñQþð	ðþ\QQQðñ
QR
þð		ñ

	
QQðQþððñúùð
ð
RþðRñ
Qà
RñRþ
á

ñR
Rþ	
	ððúùùù
ñ
Rþ	ñðúú
Q




þ	ðððñQQô

RRþQððð

òòQáñ
R
ò

þàññööøðàñRRáññ
R
Rþ
ð	òRðñáñRRþôòàññ
RáQRÿþõõääþõõõõääþõõõõõõääþõõþõõõõääþõõþõõõõääþõõþõõõõääþõõþõõõõääþõõþ
õõõõääþõõþõõääþõõþääþõõþääþõõþääþõõþääþõõþääþõõþääþõõþääþõõþõþääþõõþ
õäõþääþõõþõþääþõõþääþõõþääþõõþääþõõþääþõõþääþõõõõþääþõõõõþ
ääþõõõõþääþõõõõþääþõõõõþääþõõõõþääþõõõõääþõõääÿþääõõþääõõõõþääõõõõõõþääõõõõþõõþääõõõõþõõþääõõõõþõõþääõõõõþõõþääõõõõþ
õõþääõõþõõþääþõõþääþõõþääþõõþääþõõþääþõõþääþõõþääþõõþääþõþõõþääþõäõþ
õõþääþõþõõþääþõõþääþõõþääþõõþääþõõþääþõõþääþõõõõþääþ
õõõõþääþõõõõþääþõõõõþääþõõõõþääþõõõõþääõõõõþääõõÿþõõõõþõõõõõõþõõþõõõõþõõþõõõõþõõþõõõõþõõþõõõõþõõþ
õõõõþõõþõõõõþõõþõõþõõþõõþõõþõõþõõþõõþõõþõõþõõþõõþõõþõõþõõþõõþõõþõõþõõþõõþõõþõõþõõþõõþõõþõõþõõþõõþõõþõõþõõþõõþõõþõõþõõõõþõõþõõõõþ
õõþõõõõþõõþõõõõþõõþõõõõþõõþõõõõþõõþõõõõõõþõõõõÿþõõõõþõõõõõõþõõõõþõõþõõõõþõõþõõõõþõõþõõõõþõõþõõõõþ
õõþõõõõþõõþõõþõõþõõþõõþõõþõõþõõþõõþõõþõõþõõþõõþõõþõõþõõþõõþõõþõõþõõþõõþõõþõõþõõþõõþõõþõõþõõþõõþõõþõõþõõþõõþõõþõõþõõþõõõõþõõþ
õõõõþõõþõõõõþõõþõõõõþõõþõõõõþõõþõõõõþõõõõõõþõõõõÿþõþðþþõððþþðþõõðþþðþððõþõþþðþððõþõõðþõþðþõõðþðõþþþõõþõþõõþþþõõþ1ðþðþððþðþðÿþðõþðõõþþõþðõõþõðþðõõþþõþõõþðþðþðþõõþ õõþþþþðþðþðþ9ÿþ	òñüþ÷SUòþõñôññõþüüþõòôôòUPPPRSûþõòõõññTUôòUSSñþ÷òõñUòSôôññññTRûþURSUõõõ÷÷ôTSSUññòSþôàààTõõõ÷õòTSSSSSñòàõþPPQ÷÷õ÷õòUSSSSRSSUSTòþSPU÷÷õôñTSSRáQRQSSQSõþUSàòõñTSSSQRQRSáQQRòþñUSQSSSRò÷TRQàRQTûþôUTTSQàRàQRRQT÷þòñUSRQRSTòûþõõõôõþòùõôùþõõõôþTñõþùõÿþòññõüþTTñTTSõþõTTTTTTTñþñTTTTTTTUòþñUTUTTTTUTþUUUUUUUSTTñþUTUUUTUUUTTþUUUTUUUUTUTþòñññUUTUUTTþñTRRUòòñUUUUUUþURPàààQSñòñôUUTñþñàPSññòTSàRSTòññUôþUPRòñôòòUTñSàQSUòñSSûþ
÷PPôõ÷õòôòòñTTàRàSSUõþõPPôõôññññòòôRàPQ÷õùþUPPUññññññSPPQSUùþôUSPPQRRàPPSSñõþ÷UñUUTTTTõõõùþ÷òñòòôõ÷õ÷þòñôõ÷þ÷ùÿþ††ˆ‰þ…‰þ††…‡‰‹††ˆ‰þ		†ˆˆŠŠ…‰þ				ˆˆŠŠ††…‡‰‹þ						ŠŠ†ˆˆŠŠ‹þ								†ŠŠˆˆŠŠ‹þ										†ˆˆŠŠŠŠ‹þ			õêéöôêê			†ˆˆŠŠ†ŠŠ‹	þ		õê	õë	
÷ôêê		ˆˆŠŠ†ˆˆŠŠ‹
		þ				÷öêëëêé

øôêø


†ˆˆŠŠ‹



						éëêé	
÷èëëêê

ˆˆŠŠ



						éëé

öê		ë		


þþ


						êé

õê				


þþ


							


		


þþ


								


ÅÃþ	þ	õêë


				


Ã		
þþ	õé		öë	

	

	
ÂÆ
	
				õéêêëê		

			


ÄÆ



					õéêé		ëé			

ÂÅÇ


					õéêé÷ëêè			


þþ


					õë		õ÷ëé	

þþ


										


þþ


						


þþ


		


þ		þ	



þþ

þþþþþþþþþþÿþ+&&()þ%)þ&&%')+þ		&((**+þ				&((**”		þ						&((–•“				þ								&((—–+						þ
										&((**+								þ												&((**+										þ


											((**													



																								

þ


																				

þ


																


þþ


												


þ	þ				


								


þþ								


				


				þ											

	

								þ

												
													


																

þ


												

þ


				tt						
þþ


				


þþ


						


þ	þ	


		


þþ



þ	þ

þþþþþþþþþþÿþþøøþøøøøøøþøøøøøøøøøøþøøøøøøøøøøøøøøþøøøøøøøøøøøøøøøøøøþööøøøøøøøøøøøøøøøøøø

þö

öøøøøøøøøøøøøøø

øþ
øøø
öøøøøøøøøøø

øøþøøúùø
öøøøøøø

øøøøøþøøû¤¥ûùø
öøøö
øøøøøøøþô	ø		

ûùø
öö
øøøøøøøøþö	ô	ø

ùøö
øøøøøøøøøøþööö	ô	
øøøùö
øøøøøøøøøøøþööööööô	
øøøùúúö
øøøøøøøøøøþööñó	ööö	ôøøúúøøö
øøøøøøøøøøþööø
óó	öö
øùøøøùö
øøøøøøøøøþø
ööø
óñöøøøùúúö
øøøøøøøøøøþø
ööøøö
øøúúøøö
øøøøøøøøøøþø
öööøùøøøøö
øøøøøøøøøþøø
ö
øøøøøùö
øøøøøøøøþùø

øøöööøö
øøøøøøøøþøø
öó	ööö
øøøøøøøþö
ööø
óñöö
øøøøøþ
ó	ö
ööøøöö
ø
	
þ
ó	ö
öööö

	
þ
ó	ö
öö

	
þ
ó	ö
ö

	
þ
ó	öö

	
þ
ó	
	
þ
óÿþþøøþøøøøøøþøøøøøøøøøøþøøøøøøøøøøøøøøþøøøøøøøøøøøøøøøøøøþ


øøøøøøøøøøøøøøøøøøööþø

øøøøøøøøøøøøøøö
ôöþøø

øøøøøøøøøøö
øø
öþøøøøø

øøøøøøö
øù	öþøøøøøøø
öøøö
ø
	ô	ôöþøøøøøøøø
öö
øù	ô	öö
öþøøøøøøøøøø
öøø	ôööööööþøøøøøøøøøøø
öô	ööö	óñö
öþøøøøøøøøøø
ö
öö	óó
øööþøøøøøøøøøø
ööñó
øööö
öþøøøøøøøøø
ö
öøøööö
ø
öþøøøøøøøøøø
ööööö
øööùöþøøøøøøøøøø
ö
öö
øööööøöþøøøøøøøøø
ö

øöööööööþøøøøøøøø
öùöööööööööþøøøøøøøø
öøöööö	óñööþøøøøøøø
ööö	óó
øööþøøøøø
ööñó
øöö
öþ
	
ø
ööøøöö
ö	ó
þ
	

öööö
ö	ó
þ
	

öö
ö	ó
þ
	

ö
ö	ó
þ
	

öö	ó
þ
	
	ó
þó
ÿþUUþUòUUþUòþRUUþUòþRRRþUòþRþRþUòþ"$þRþUòþ"$$"þUòþ""þððòòþòòððþòòòòððþòòòòòòððþòòòòòòòòððþUUTTòòòòòòòòððþñUTTSRRRòòòòòòòòððòþ443TSSRRRRRRòòòòòòòòðñþ4433222RRRRRRRRRòòòòòòòôþ4433222222RRRRRRRRRSòòòòòôþ44332222222222SRRRRRSSTUòòòôþ443322222222222222SSSSTTUSSSòô44332222222222222222222UUSSSTUòô77222222222222222222222222TTUUñô777722222222222222222222334UUUñô777777222222222222222233444Uññòôþ7777772222222222223344445ñþñôþ7777772222222233444455þñôþ777777222233444455þòôþ77777733444455þòôþ
7777774455þ
ôòþ777755þòôþ77ÿþ44þ443322þ4433222222þ44332222222222þ443322222222222222þ4433222222222222222222þððþ44332222222222222222222222þòòðð3322222222222222222222222233òòòòðð22222222222222222222223344òòòòòòðð222222222222222222334444òòòòòòòòðð2222222222222233444455òòòòòòòòòòðð222222222233444455þòôòòòòòòòòòòðð22222233444455þòôþòòòòòòòòòòðñ2233444455þòôþòòòòòòòòòô33444455þòôþòòòòòòòô444455þ
òôþòòòòòô4455þôòþ
òòòô55þòôþòôþòôþòôþòôþòôÿþUUþUòUUþUòþRUUþUòþRRRþUòþRþRþUòþ34þRþUòþ3443þUòþ33þððòþòòððþòòòòððþòòòòòòððþòòòòòòòòððþUUTTòòòòòòòòððþññòþUUTTSRSSòòòòòòòòððòþññþòUTTSSRRRRSSòòòòòòòòðñþññòþUUTTRRRRRRRRRRSSòòòòòòòôþññþòUTTRRRRRRRRRRRRRRSSòòòòòôññòþUUTTRRRRRRRRRRRRRRRRRRSSòòòôþòUTTRRRRRRRRRRRRRRRRRRRRRRSSòôUUTTRRRRRRRRRRRRRRRRRRRRññòRTUòôWWRRRRRRRRRRRRRRRRRRRRññRRòTUUñôWWWWRRRRRRRRRRRRRRRRññòRTTòUUUñôWWWWWWRRRRRRRRRRRRññRRòTUUòUññòôþWWWWWWRRRRRRRRññòRTTòUUUññþòôþWWWWWWRRRRRRRRòTUUòUññþòôþWWWWWWRRRRTTòUUUññþòôþWWWWWWTTUUòUññþòôþ
WWWWWWUUññþ
ôòþWWWWññþôòôþWWþôÿþññþññòþññþòUþññòþUUTTRRþññþòUTTRRRRRRþññòþUUTTRRRRRRRRRRþññþòUTTRRRRRRRRRRRRRRþ
òþUUTTRRRRRRRRRRRRRRRRRRþññððþòUTTRRRRRRRRRRRRRRRRRRRRññòþòòððTTRRRRRRRRRRRRRRRRRRRRññRRòTòòòòððRRRRRRRRRRRRRRRRRRññòRTTòUòòòòòòððRRRRRRRRRRRRRRññRRòTUUòUòòòòòòòòððRRRRRRRRRRññòRTTòUUUññòòòòòòòòòòððRRRRRRññRRòTUUòUññþòôòòòòòòòòòòððRRRRòRTTòUUUññþòôþòòòòòòòòòòðñRRòTUUòUññþòôþòòòòòòòòòôTTòUUUññþòôþòòòòòòòôUUòUññþ
òôþòòòòòôUUññþôòôþ	òòòôññþôþòôþòôþòôþòôþòôþòôþôòôþôÿþ

ñäñ
þö	ñäñþRñ
ôòññññø
òñþñôôôñää
äøô	òþôòòòòòññ

ôòþø	ôôô	

RRøþøRññRòþøö
Ròòñòøþ
öññòòñ	ñ
þøöñRòôôññøþ	
òRñôôRñ	ñöþôôòRñññòôRñ	ôþñññññRôþññòöòøþøö
äRøñøøþ
öòò
òòòòôöñ

þø	ññôö	
øþ
ôñññäòôô		
þøø	òññäñòôô		
øþ	
ôòñññòôô	ø	þ	ôøøôòô	
øø	
þ
ô	øøøø
	ô
þ	ôòô	
ÿþYþZ¢þZþ	¢¢YþYZY¡Yþ	]ZYþZ]]]ZZZ¢þ]]ZZþY^]]]\þ]]]ôþY¢]]\\Yþ]YY¢Y\]ñþôYY]ú\ZYYYYZ\\\]YôöþZ¡ZZZ\\ZZZZ\¢]ñôþ[¡Y\\\
ZY[
ôôþöô[
ðY££YZ	ñ	Z]ñôþ
[
ññ¢£ññ]Zôþ	
úú
ñôñ]]ôñô^þúúúúúññ¢ñôñþ
úúúúú
ÿ
þ

þ
ôòòò	þ
òòòòòòòò	þòòòòòòòô
ôþòññòòô
LôþòññññLLLôþññññññLLLLLôþññññññLLLLLôþññññññLLL4LLôþññññññLLLLLLòþôñ—ôññLLLJ	òôþ—––¦ñññLJ	òôôUTþS—¥SZYôòñ	òôôUTTTUþTRSS–—¥YZYYòôôUT•UTTTþ
VSRRS¥—––RTTUT•UT•UTTVþVVVSQRSSSUTT•UT•UTTVZXþVVVVVSQRSTTTUT•UTTVZX[þ	VVXVVVVSQRTTTTUTTVZXXXZþ	VVXSXVVVVSQTTTTVZXXXX[þ
VVXSXSVVVVVSQSZXXXXXXZþ
VVXSXSVVVVVVVZXXXXXX[þXZVVXSVVVVVVVXXXXXXXZþXZVVVVVVVVZXXXXX[ZþXZVVVVVVXXXX[ZþXZVVVZXX[ZþXZVX[Zþ[[ÿ
þ

þ
ôòòò	þ
òòòòòòòò	þòòòòòòòô
ôþòññòòô
LôþòññññLLLôþññññññLLLLLôþññññññL5LLLôþññññññLLL4LLôþññññññLLLLLLòþôñ—ôññLLLJ	òôþ—––¦ñññLJ	òôôUTþS—¥SZYôòñ	òôôUTTTUþTRSS–—¥YZYYòôôUT•UTTTþ
VSRRS¥—––RTTUT•UT•UTTVþVVVSQRSSSUTT•UT•UTTVZXþVVVVVSQRSTTTUT•UTTVZX[þ	VVXVVVVSQRTTTTUTTVZXXXZþ	VVXSXVVVVSQTTTTVZXXXX[þ
VVXSXSVVVVVSQSZXXXXXXZþ
VVXSXSVVVVVVVZXXXXXX[þXZVVXSVVVVVVVXXXXXXXZþXZVVVVVVVVZXXXXX[ZþXZVVVVVVXXXX[ZþXZVVVZXX[ZþXZVX[Zþ[[ÿ
þ

þ
ôòòò	þ
òòòòòòòò	þòòòòòòòô
ôþòññòòô
LôþòññññLLLôþññññññLLLLLôþññññññL7LLLôþññññññLLL5LLôþññññññLLLLLLòþôñ—ôññLLLJ	òôþ—––¦ñññLJ	òôôUTþS—¥SZYôòñ	òôôUTTTUþTRSS–—¥YZYYòôôUT•UTTTþ
VSRRS¥—––RTTUT•UT•UTTVþVVVSQRSSSUTT•UT•UTTVZXþVVVVVSQRSTTTUT•UTTVZX[þ	VVXVVVVSQRTTTTUTTVZXXXZþ	VVXSXVVVVSQTTTTVZXXXX[þ
VVXSXSVVVVVSQSZXXXXXXZþ
VVXSXSVVVVVVVZXXXXXX[þXZVVXSVVVVVVVXXXXXXXZþXZVVVVVVVVZXXXXX[ZþXZVVVVVVXXXX[ZþXZVVVZXX[ZþXZVX[Zþ[[ÿ
þ

þ
ôòòò	þ
òòòòòòòò	þòòòòòòòô
ôþòññòòô
LôþòññññLLLôþññññññLLLLLôþññññññLLLLLôþññññññLLL4LLôþññññññLLLLLLòþôñ—ôññLLLJ	òôþ—––¦ñññLJ	òôôUTþS—¥SZYôòñ	òôôUTTTUþTRSS–—¥YZYYòôôUT•UTTTþ
VSRRS¥—––RTTUT•UT•UTTVþVVVSQRSSSUTT•UT•UTTVZXþVVVVVSQRSTTTUT•UTTVZX[þ	VVXVVVVSQRTTTTUTTVZXXXZþ	VVXSXVVVVSQTTTTVZXXXX[þ
VVXSXSVVVVVSQSZXXXXXXZþ
VVXSXSVVVVVVVZXXXXXX[þXZVVXSVVVVVVVXXXXXXXZþXZVVVVVVVVZXXXXX[ZþXZVVVVVVXXXX[ZþXZVVVZXX[ZþXZVX[Zþ[[ÿ